import type { Machine, MachineZone } from "./machines";

export const gluteZone: MachineZone = {
  title: "Glutei",
  eyebrow: "Allenamento per gruppi muscolari · Anche e glutei",
  heroTitle: ["COSTRUISCI", "I TUOI", "GLUTEI."],
  heroLead:
    "Un’area dedicata alla spinta d’anca e al lavoro mirato sui glutei: macchine guidate, Hip Thrust dedicate e stazioni Sidea, Life Fitness e Panatta. Apri la scheda e scopri come usare ogni postazione.",
  manifestoTitle: ["NON UN ACCESSORIO.", "UN FONDAMENTALE."],
  manifesto: [
    "I glutei non sono un dettaglio estetico: sono il motore dell’estensione dell’anca, della stabilità del bacino e di tanta forza trasferibile a squat, corsa e sport.",
    "Revenge Gym dedica loro un’area propria perché in sala contano strumenti veri: Gluteus Machine, Master Gluteus Panatta, Hip Thrust orizzontale e verticale, Sidea a bilanciere, Abductor e Adductor.",
    "Ogni scheda spiega marchio, ruolo allenante e come eseguire il gesto con qualità. Qui non si improvvisa con panche sparse: si allena con metodo.",
  ],
};

export const gluteMachines: Machine[] = [
  {
    id: "abductor-life-fitness",
    number: "01",
    name: "Abductor",
    brand: "Life Fitness",
    category: "Anche e glutei",
    image: "/photos/machines/gambe/abductor-life-fitness.webp",
    alt: "Abductor Life Fitness in Revenge Gym",
    tagline: "Apertura controllata, gluteo medio e stabilità del bacino.",
    brandNote: [
      "L’Abductor Life Fitness è una selettorizzata dedicata all’abduzione dell’anca. Nei club di fascia professionale completa il lavoro su glutei e stabilità del bacino con la solidità tipica del marchio.",
      "Troppe palestre trascurano queste stazioni o le trattano come macchine “secondarie da angolo”. Revenge le tiene in primo piano, pulite, ordinate e integrate in un’area gambe davvero completa.",
      "È un altro tassello del messaggio qualità: qui ogni gestualità utile ha una macchina degna di questo nome.",
    ],
    lead: [
      "L’abduzione non è solo estetica laterale: rafforza gluteo medio e muscolatura che tiene il bacino stabile sotto carico. È centrale nella prevenzione, nel controllo dello squat e nelle attività con cambi di direzione.",
      "Inserirla in un programma di arti inferiori di qualità eleva il livello della seduta: spinte forti, isolamento intelligente, anche stabili. Esattamente l’approccio da atleta.",
      "In Revenge Gym la trovi nel contesto giusto — sala curata, macchine professionali, cultura dell’allenamento serio.",
    ],
    qualityEdge:
      "Life Fitness anche sull’abductor conferma la linea Revenge: brand forti su tutta la linea, non solo sulla macchina “di copertina”.",
    focus: "Abduzione dell’anca e stabilità laterale",
    primaryMuscles: ["Gluteo medio", "Gluteo minore", "Tensore della fascia lata"],
    secondaryMuscles: ["Stabilizzatori del bacino e del tronco"],
    trainingRole: [
      "Accessorio di stabilità e glutei laterali",
      "Attivazione prima di squat/pressa o finisher a fine seduta",
      "Supporto a ginocchia e bacino nei gesti pesanti",
      "Elemento di completezza nei programmi glutei",
    ],
    cues: [
      "Schiena stabile, apertura controllata",
      "Non strappare il pacco pesi",
      "Chiudi lentamente mantenendo tensione",
      "Respira senza trattenere",
      "Scegli un’ampiezza utile, non estrema a tutti i costi",
    ],
    programming: [
      "3×12–20 a controllo elevato",
      "Attivazione: 2×15 prima di squat/pressa",
      "Finisher glutei: 2×15–20",
      "Superserie con Adductor",
    ],
    errors: [
      "Usare lo slancio delle anche",
      "Inarcare eccessivamente la schiena",
      "Scegliere un carico che riduce l’escursione utile",
      "Eseguire serie frettolose “tanto è leggero”",
    ],
    trainer:
      "Qui conta la qualità del cerchio di movimento, non il numero sul carrello. Nelle sale serie, anche l’accessorio si esegue da professionisti.",
  },
  {
    id: "adductor-life-fitness",
    number: "02",
    name: "Adductor",
    brand: "Life Fitness",
    category: "Anche e glutei",
    image: "/photos/machines/gambe/adductor-life-fitness.webp",
    alt: "Adductor Life Fitness in Revenge Gym",
    tagline: "Chiusura dell’anca, adduttori forti, coscia completa.",
    brandNote: [
      "L’Adductor Life Fitness lavora la catena mediale della coscia. In abbinamento all’Abductor permette di allenare in modo mirato i muscoli che chiudono le anche, spesso trascurati rispetto a presse e squat.",
      "Nelle palestre di qualità queste due macchine viaggiano in coppia, tenute in ordine e integrate nei programmi. Revenge Gym segue esattamente questa logica da club professionale.",
      "È un segnale chiaro per chi entra in sala: qui non manca il pezzo “scomodo” o meno spettacolare. C’è tutto ciò che serve per costruire arti inferiori completi.",
    ],
    lead: [
      "Gli adduttori contribuiscono a stabilità, cambi di direzione e completezza della coscia. Allenarli in macchina consente serie pulite e progressioni semplici, soprattutto in ipertrofia e nel lavoro di controllo dell’anca.",
      "Un atleta che vuole qualità non ignora la catena mediale. La Adductor Life Fitness rende questo lavoro preciso, misurabile e sostenibile nel tempo.",
      "In un ambiente maniacalmente ordinato e pulito, anche questo gesto “di dettaglio” diventa parte di una cultura allenante superiore.",
    ],
    qualityEdge:
      "Completezza = qualità. Revenge non seleziona solo le macchine più fotogeniche: allestisce un’area gambe davvero professionale.",
    focus: "Adduttori e catena mediale",
    primaryMuscles: ["Adduttore lungo", "Adduttore grande", "Adduttore breve", "Pettineo / gracile"],
    secondaryMuscles: ["Stabilizzatori del bacino"],
    trainingRole: [
      "Accessorio per completezza della coscia",
      "Complemento a squat, pressa e affondi",
      "Utile in prevenzione e controllo dell’anca",
      "Coppia naturale con Abductor nei finisher",
    ],
    cues: [
      "Regola l’ampiezza iniziale sulla tua mobilità",
      "Chiudi con controllo, senza strappi",
      "Mantieni il bacino stabile",
      "Ritorna lentamente alla posizione di partenza",
      "Non forzare aperture dolorose",
    ],
    programming: [
      "3×12–20",
      "Superserie con Abductor",
      "Dopo affondi o belt squat: 2–3×15",
      "Giorno glutei/anche: blocco dedicato 4 serie totali",
    ],
    errors: [
      "Forzare un’apertura eccessiva",
      "Usare slancio per chiudere",
      "Trattenere il respiro per tutta la serie",
      "Trattarlo come esercizio “di riempimento” senza intenzionalità",
    ],
    trainer:
      "Mobilità e controllo prima del carico. Gli adduttori rispondono bene alle serie medie e pulite — da palestra che punta alla qualità del gesto.",
  },
  {
    id: "gluteus-machine-life-fitness",
    number: "03",
    name: "Gluteus Machine",
    brand: "Life Fitness",
    category: "Anche e glutei",
    image: "/photos/machines/gambe/gluteus-machine-life-fitness.webp",
    alt: "Gluteus Machine Life Fitness in Revenge Gym",
    tagline: "Estensione dell’anca mirata, gluteo sotto tensione.",
    brandNote: [
      "La Gluteus Machine Life Fitness è progettata per isolare l’estensione dell’anca. Nei club di fascia alta permette di concentrare il lavoro sul grande gluteo con percorso guidato e regolazioni chiare.",
      "Avere una macchina dedicata ai glutei — e non solo squat generici — è tipico delle sale che ascoltano davvero le esigenze di atlete e atleti moderni, senza abbassare lo standard costruttivo.",
      "Revenge Gym la inserisce in un ecosistema già ricco (hip thrust, Master Gluteus Panatta, abductor/adductor): un’offerta da centro premium, non da palestra “basta che ci sia”.",
    ],
    lead: [
      "Se vuoi dare attenzione specifica ai glutei oltre a squat e presse, questa macchina è lo strumento giusto. Ideale per ipertrofia, attivazione e per chi vuole qualità di contrazione senza sovraccaricare la schiena come in alcuni stacchi.",
      "Il lavoro isolato sui glutei, fatto su una Life Fitness, ha un altro sapore: fluidità, ripetibilità, focus. È allenamento di precisione.",
      "In una sala pulita e ordinata, l’esperienza si completa: trovi la postazione pronta, regoli, esegui, esci con un lavoro fatto bene.",
    ],
    qualityEdge:
      "Revenge tratta i glutei con la stessa serietà della forza su pressa e rack. È una palestra per chi vuole risultati, non scorciatoie di prezzo.",
    focus: "Ipertrofia e attivazione dei glutei",
    primaryMuscles: ["Grande gluteo"],
    secondaryMuscles: ["Ischiocrurali", "Stabilizzatori del bacino"],
    trainingRole: [
      "Accessorio glutei dedicato di alto livello",
      "Attivazione prima delle spinte",
      "Finisher a fine seduta gambe/glutei",
      "Elemento chiave nei mesocicli di ipertrofia glutea",
    ],
    cues: [
      "Regola il pad e l’assetto finché senti il gluteo",
      "Estendi l’anca senza inarcare troppo la lombare",
      "Pausa breve in chiusura",
      "Ritorno controllato",
      "Se non senti il target, regola prima di caricare",
    ],
    programming: [
      "3–4×10–15",
      "Attivazione: 2×12–15",
      "Superserie con hip thrust",
      "Giorno glutei: 4 serie di qualità a buffer tecnico",
    ],
    errors: [
      "Tirare con la schiena invece che con l’anca",
      "Accorciare l’escursione",
      "Usare troppo carico e perdere la contrazione",
      "Ignorare le regolazioni “per fare prima”",
    ],
    trainer:
      "Se non senti il gluteo, non aggiungere piolini: regola l’assetto. Le macchine di qualità premiano chi ha pazienza tecnica.",
  },
  {
    id: "master-gluteus-panatta",
    number: "04",
    name: "Master Gluteus",
    brand: "Panatta",
    category: "Anche e glutei",
    image: "/photos/machines/gambe/master-gluteus-panatta.webp",
    alt: "Master Gluteus Panatta in Revenge Gym",
    tagline: "Specialista Panatta per glutei, precisione italiana.",
    brandNote: [
      "Il Master Gluteus Panatta rientra nelle macchine specialistiche del brand italiano. È pensato per un lavoro di alto livello sull’estensione dell’anca, con la cura biomeccanica tipica delle linee Panatta da club professionali.",
      "Mettere in sala sia Life Fitness sia Panatta sui glutei non è sfizio: è standard da strength boutique. Due cinematiche, due sensazioni, una sola ossessione — la qualità.",
      "Per un atleta di Ladispoli che confronta le palestre, pezzi così fanno capire subito dove si allena chi vuole il meglio.",
    ],
    lead: [
      "Il Master Gluteus offre una postazione dedicata e distintiva per i glutei. Ruotare angoli e sensazioni aumenta la qualità del lavoro senza ripetere sempre lo stesso schema.",
      "È la macchina che cerchi quando il programma chiede dettaglio, pompaggio e progressione mirata. In un contesto Revenge — ordine, pulizia, staff attento — diventa ancora più efficace perché puoi concentrarti solo sull’esecuzione.",
      "Chi ama allenarsi “da professionista” riconosce queste postazioni al volo: non sono riempitivi, sono strumenti di mestiere.",
    ],
    qualityEdge:
      "Panatta Master Gluteus è il tipo di macchina che una palestra mette in sala solo se ha deciso di puntare in alto. Revenge ha deciso esattamente questo.",
    focus: "Lavoro specialistico sui glutei",
    primaryMuscles: ["Grande gluteo"],
    secondaryMuscles: ["Ischiocrurali", "Core e stabilizzatori"],
    trainingRole: [
      "Macchina prioritaria nei giorni glutei",
      "Alternativa/rotazione rispetto ad altre glute machine",
      "Alto valore in ipertrofia mirata",
      "Scelta da atleti che periodizzano gli angoli di lavoro",
    ],
    cues: [
      "Assetto preciso prima del carico",
      "Spingi con l’anca, non con la lombare",
      "Contrazione consapevole in chiusura",
      "Escursione completa ma controllabile",
      "Tratta ogni serie come lavoro di precisione Panatta",
    ],
    programming: [
      "3–4×8–15",
      "Piramide: 12 / 10 / 8 aumentando il carico",
      "Finisher: 2×15 tecniche",
      "Rotazione bisettimanale con Gluteus Life Fitness",
    ],
    errors: [
      "Compensare con la schiena",
      "Muovere il bacino fuori traiettoria",
      "Inseguire il carico perdendo il feeling muscolare",
      "Saltare le regolazioni",
    ],
    trainer:
      "Due macchine glutei non sono un doppione: sono due voci diverse nella stessa orchestra. In Revenge l’orchestra è di livello.",
  },
  {
    id: "hip-thrust-orizzontale",
    number: "05",
    name: "Hip Thrust Orizzontale",
    brand: "Plate Loaded",
    category: "Anche e glutei",
    image: "/photos/machines/gambe/hip-thrust-orizzontale.webp",
    alt: "Hip Thrust orizzontale in Revenge Gym",
    tagline: "Spinta d’anca orizzontale, glutei al centro.",
    brandNote: [
      "Le postazioni di Hip Thrust professionali permettono di eseguire la spinta d’anca in modo guidato e ripetibile. La variante orizzontale offre un assetto stabile per carichi progressivi e serie di qualità sul grande gluteo.",
      "Nelle sale moderne di alto livello l’Hip Thrust non è più un esercizio “di moda”: è un fondamentale per forza e ipertrofia dei glutei. Revenge lo tratta come tale, con postazioni dedicate e ambiente impeccabile.",
      "Avere thrust guidate in sala eleva l’esperienza rispetto a soluzioni improvvisate con panca e bilanciere in spazi caotici.",
    ],
    lead: [
      "L’Hip Thrust è uno dei gesti più efficaci per sviluppare i glutei. In macchina, traiettoria e appoggi aiutano a concentrarsi sull’estensione dell’anca e sulla chiusura in alto, riducendo le compensazioni tipiche della versione totalmente libera.",
      "Per atleti che vogliono qualità, la postazione dedicata cambia tutto: progressioni chiare, setup rapido, focus sul muscolo. È allenamento efficiente e professionale.",
      "In Revenge Gym questo si inserisce in un’area gambe già da club top: non un pezzo isolato, ma parte di un sistema.",
    ],
    qualityEdge:
      "Una palestra che investe su Hip Thrust dedicate sta dicendo agli atleti: i tuoi obiettivi contano, e li supportiamo con strumenti veri.",
    focus: "Spinta d’anca per glutei",
    primaryMuscles: ["Grande gluteo"],
    secondaryMuscles: ["Ischiocrurali", "Core", "Adduttori in assistenza"],
    trainingRole: [
      "Esercizio primario nei giorni glutei",
      "Secondo blocco dopo squat/pressa",
      "Progressione chiara di carico e ripetizioni",
      "Base per chi costruisce forza estensoria dell’anca",
    ],
    cues: [
      "Mento neutro, costole basse",
      "Spingi il bacino in alto senza inarcare eccessivamente",
      "Pausa in chiusura stringendo i glutei",
      "Scendi con controllo",
      "Carica solo quando la chiusura resta pulita",
    ],
    programming: [
      "Forza: 4×6–8",
      "Ipertrofia: 3–4×8–12",
      "Pump: 2×15–20",
      "Abbinamento con Abductor o Master Gluteus",
    ],
    errors: [
      "Iperestendere la lombare in alto",
      "Spingere con i quadricipiti dimenticando l’anca",
      "Usare un ROM incompleto solo per caricare di più",
      "Setup frettoloso e assetto instabile",
    ],
    trainer:
      "In alto conta la chiusura del gluteo, non quanto “spezzi” la schiena. Su una postazione di qualità, la precisione paga più dell’ego.",
  },
  {
    id: "hip-thrust-verticale",
    number: "06",
    name: "Hip Thrust Verticale",
    brand: "Plate Loaded",
    category: "Anche e glutei",
    image: "/photos/machines/gambe/hip-thrust-verticale.webp",
    alt: "Hip Thrust verticale in Revenge Gym",
    tagline: "Stessa famiglia, angolo diverso, nuovo stimolo.",
    brandNote: [
      "La versione verticale dell’Hip Thrust cambia l’orientamento del corpo e la sensazione di spinta rispetto alla postazione orizzontale. Avere entrambe in sala è tipico dei centri che vogliono adattare l’esercizio a preferenze, mobilità e obiettivi.",
      "È un lusso allenante concreto: non “due pezzi uguali”, ma due soluzioni di qualità per lo stesso gesto fondamentale.",
      "Revenge Gym le offre in un contesto di ordine e cura che fa percepire subito la differenza rispetto a sale affollate e attrezzature trascurate.",
    ],
    lead: [
      "L’Hip Thrust verticale è un’altra arma per i glutei. Può risultare più comoda o più intensa a seconda dell’atleta: l’importante è mantenere la qualità dell’estensione d’anca e una chiusura controllata.",
      "Nei programmi di alto livello si ruotano e si confrontano le varianti, scegliendo quella più adatta al proprio corpo e alla propria progressione.",
      "Con due thrust dedicate, Revenge dimostra ancora una volta di costruire l’area gambe per chi vuole il massimo dallo stimolo.",
    ],
    qualityEdge:
      "Due Hip Thrust in sala sono un manifesto: qui si investe sull’allenamento vero, non sul ribasso del mensile.",
    focus: "Spinta d’anca su assetto verticale",
    primaryMuscles: ["Grande gluteo"],
    secondaryMuscles: ["Ischiocrurali", "Core"],
    trainingRole: [
      "Rotazione con Hip Thrust orizzontale",
      "Ipertrofia glutei di qualità",
      "Accessorio pesante dopo le spinte",
      "Scelta individuale in base a feeling e mobilità",
    ],
    cues: [
      "Trova un assetto in cui senti subito i glutei",
      "Estendi l’anca senza perdere il controllo del bacino",
      "Evita di “tirare” con la lombare",
      "Ritorno lento e continuo",
      "Confronta il feeling con la versione orizzontale e scegli con criterio",
    ],
    programming: [
      "3–4×8–12",
      "Alterna settimane orizzontale / verticale",
      "Superserie con Abductor",
      "Mesociclo dedicato 4 settimane su una sola variante",
    ],
    errors: [
      "Assetto frettoloso prima della serie pesante",
      "ROM tagliato",
      "Carico eccessivo con perdita di contrazione",
      "Usare entrambe nella stessa seduta senza recupero sufficiente",
    ],
    trainer:
      "Se una delle due thrust ti “parla” di più, usala come primaria e tieni l’altra come variante. La qualità sta anche nella scelta intelligente.",
  },
  {
    id: "hip-thrust-sidea",
    number: "07",
    name: "Hip Thrust",
    brand: "Sidea",
    category: "Anche e glutei",
    image: "/media/new-machines/sidea-hip-thrust.webp",
    alt: "Hip Thrust Sidea in Revenge Gym",
    tagline: "Stazione dedicata alla spinta d’anca, setup rapido e chiusura di qualità.",
    brandNote: [
      "La Sidea Hip Thrust Platform Bench 9122 è una stazione professionale pensata per eseguire l’Hip Thrust con bilanciere senza improvvisare su panca piana.",
      "Piattaforma antiscivolo, rullo semi-cilindrico per le scapole e supporti laterali riducono i tempi di setup e aiutano a concentrarsi sull’estensione dell’anca.",
      "Avere una postazione Sidea dedicata conferma lo standard Revenge: strumenti veri per i glutei, non soluzioni di fortuna.",
    ],
    lead: [
      "L’Hip Thrust Sidea è uno dei gesti più efficaci per sviluppare i glutei. La stazione dedicata rende setup e progressione più semplici rispetto a panca e bilanciere improvvisati.",
      "Piedi stabili sulla piattaforma, scapole sul rullo e bilanciere imbottito sulle anche: puoi concentrarti sulla chiusura del grande gluteo e su un ritorno controllato.",
      "In Revenge Gym completa un’area glutei già ricca di macchine guidate, offrendo anche la variante a bilanciere su stazione professionale.",
    ],
    qualityEdge:
      "Una palestra che investe su una Hip Thrust dedicata Sidea dice agli atleti che i glutei meritano strumenti di livello, non scorciatoie.",
    focus: "Spinta d’anca con bilanciere su stazione dedicata",
    primaryMuscles: ["Grande gluteo"],
    secondaryMuscles: ["Ischiocrurali", "Adduttori", "Core", "Quadricipite in assistenza"],
    trainingRole: [
      "Esercizio primario nei giorni glutei",
      "Secondo blocco dopo squat o presse",
      "Progressione chiara di carico a dischi",
      "Alternativa o complemento alle Hip Thrust guidate",
    ],
    cues: [
      "Scapole stabili sul rullo, mento neutro",
      "Spingi il bacino in alto senza inarcare eccessivamente",
      "Pausa in chiusura stringendo i glutei",
      "Scendi con controllo e piedi pieni sulla piattaforma",
      "Carica solo quando la chiusura resta pulita",
    ],
    programming: [
      "Forza: 4×6–8",
      "Ipertrofia: 3–4×8–12",
      "Pump: 2×15–20",
      "Abbinamento con Abductor o Master Gluteus",
    ],
    errors: [
      "Iperestendere la lombare in alto",
      "Spingere soprattutto con i quadricipiti",
      "Posizionare male le scapole sul rullo",
      "Usare un ROM incompleto solo per caricare di più",
    ],
    trainer:
      "In alto conta la chiusura del gluteo, non quanto “spezzi” la schiena. Sulla Sidea la precisione del setup paga più dell’ego.",
  },
];

export function getGluteMachine(id: string) {
  return gluteMachines.find((machine) => machine.id === id);
}
